language: node_js

os:
  - linux
  - windows

node_js:
  - node
  - 8

cache: yarn

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      yarn build && yarn spec
    else
      yarn test
    fi
