environment:
  matrix:
    - nodejs_version: 7
    - nodejs_version: 6

test_script:
  - node --version
  - yarn --version
  - yarn test

install:
  - choco install wget
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  choco install wget
  - yarn

cache:
  - "%LOCALAPPDATA%/Yarn"

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1
